--select *
  --update m set Mun_type_id=501
  update m set m.Prov_Id=p.Prov_Id
from (values
('!Kheis, Northern Cape'),
('//Khara Hais, Northern Cape'),
('Abaqulusi, KwaZulu-Natal'),
('Aganang, Limpopo'),
('Alfred Duma, KwaZulu-Natal'),
('Amahlathi, Eastern Cape'),
('Ba-Phalaborwa, Limpopo'),
('Baviaans, Eastern Cape'),
('Beaufort West, Western Cape'),
('Bela-Bela, Limpopo'),
('Bergrivier, Western Cape'),
('Big Five Hlabisa, KwaZulu-Natal'),
('Bitou, Western Cape'),
('Blouberg, Limpopo'),
('Blue Crane Route, Eastern Cape'),
('Breede Valley, Western Cape'),
('Buffalo City, Eastern Cape'),
('Bushbuckridge, Mpumalanga'),
('Cape Agulhas, Western Cape'),
('Cederberg, Western Cape'),
('Chief Albert Luthuli, Mpumalanga'),
('City of Cape Town, Western Cape'),
('City of Johannesburg, Gauteng'),
('City of Matlosana, North West'),
('City of Tshwane, Gauteng'),
('Dannhauser, KwaZulu-Natal'),
('Dawid Kruiper, Northern Cape'),
('Dihlabeng, Free State'),
('Dikgatlong, Northern Cape'),
('Dipaleseng, Mpumalanga'),
('Ditsobotla, North West'),
('Dr Beyers Naude, Eastern Cape'),
('Dr JS Moroka, Mpumalanga'),
('Dr Nkosazana Dlamini Zuma, KwaZulu-Natal'),
('Dr Pixley Ka Isaka Seme, Mpumalanga'),
('Drakenstein, Western Cape'),
('Ekurhuleni, Gauteng'),
('Elias Motsoaledi, Limpopo'),
('Elundini, Eastern Cape'),
('Emadlangeni, KwaZulu-Natal'),
('Emakhazeni, Mpumalanga'),
('Emalahleni, Eastern Cape'),
('Emalahleni, Mpumalanga'),
('Emfuleni, Gauteng'),
('Emnambithi/Ladysmith, KwaZulu-Natal'),
('Emthanjeni, Northern Cape'),
('Endumeni, KwaZulu-Natal'),
('Engcobo, Eastern Cape'),
('Enoch Mgijima, Eastern Cape'),
('Ephraim Mogale, Limpopo'),
('Ezingoleni, KwaZulu-Natal'),
('Fetakgomo, Limpopo'),
('Ga-Segonyana, Northern Cape'),
('Gamagara, Northern Cape'),
('Gariep, Eastern Cape'),
('George, Western Cape'),
('Govan Mbeki, Mpumalanga'),
('Great Kei, Eastern Cape'),
('Greater Giyani, Limpopo'),
('Greater Kokstad, KwaZulu-Natal'),
('Greater Letaba, Limpopo'),
('Greater Taung, North West'),
('Greater Tubatse, Limpopo'),
('Greater Tubatse/Fetakgomo, Limpopo'),
('Greater Tzaneen, Limpopo'),
('Hantam, Northern Cape'),
('Hessequa, Western Cape'),
('Hlabisa, KwaZulu-Natal'),
('Ikwezi, Eastern Cape'),
('Imbabazane, KwaZulu-Natal'),
('Impendle, KwaZulu-Natal'),
('Indaka, KwaZulu-Natal'),
('Ingwe, KwaZulu-Natal'),
('Inkosi Langalibalele, KwaZulu-Natal'),
('Inkwanca, Eastern Cape'),
('Intsika Yethu, Eastern Cape'),
('Inxuba Yethemba, Eastern Cape'),
('Joe Morolong, Northern Cape'),
('Jozini, KwaZulu-Natal'),
('Kagisano/Molopo, North West'),
('Kai !Garib, Northern Cape'),
('Kamiesberg, Northern Cape'),
('Kannaland, Western Cape'),
('Kareeberg, Northern Cape'),
('Karoo Hoogland, Northern Cape'),
('Kgatelopele, Northern Cape'),
('Kgetlengrivier, North West'),
('Khâi-Ma, Northern Cape'),
('King Sabata Dalindyebo, Eastern Cape'),
('Knysna, Western Cape'),
('Kopanong, Free State'),
('Kou-Kamma, Eastern Cape'),
('Kouga, Eastern Cape'),
('Kwa Sani, KwaZulu-Natal'),
('KwaDukuza, KwaZulu-Natal'),
('Laingsburg, Western Cape'),
('Langeberg, Western Cape'),
('Lekwa, Mpumalanga'),
('Lekwa-Teemane, North West'),
('Lepele-Nkumpi, Limpopo'),
('Lephalale, Limpopo'),
('Lesedi, Gauteng'),
('Letsemeng, Free State'),
('Local Municipality of Madibeng, North West'),
('Lukanji, Eastern Cape'),
('Mafikeng, North West'),
('Mafube, Free State'),
('Magareng, Northern Cape'),
('Makana, Eastern Cape'),
('Makhado, Limpopo'),
('Makhado-Thulamela, Limpopo'),
('Makhuduthamaga, Limpopo'),
('Maletswai, Eastern Cape'),
('Maluti a Phofung, Free State'),
('Mamusa, North West'),
('Mandeni, KwaZulu-Natal'),
('Mangaung, Free State'),
('Mantsopa, Free State'),
('Maphumulo, KwaZulu-Natal'),
('Maquassi Hills, North West'),
('Maruleng, Limpopo'),
('Masilonyana, Free State'),
('Matatiele, Eastern Cape'),
('Matjhabeng, Free State'),
('Matzikama, Western Cape'),
('Mbhashe, Eastern Cape'),
('Mbizana, Eastern Cape'),
('Mbombela, Mpumalanga'),
('Mbombela, Mpumalanga'),
('Merafong City, Gauteng'),
('Metsimaholo, Free State'),
('Mfolozi, KwaZulu-Natal'),
('Mhlontlo, Eastern Cape'),
('Midvaal, Gauteng'),
('Mier, Northern Cape'),
('Mkhambathini, KwaZulu-Natal'),
('Mkhondo, Mpumalanga'),
('Mnquma, Eastern Cape'),
('Modimolle, Limpopo'),
('Modimolle/Mookgophong, Limpopo'),
('Mogalakwena, Limpopo'),
('Mogale City, Gauteng'),
('Mohokare, Free State'),
('Molemole, Limpopo'),
('Mookgopong, Limpopo'),
('Moqhaka, Free State'),
('Moretele, North West'),
('Moses Kotane, North West'),
('Mossel Bay, Western Cape'),
('Mpofana, KwaZulu-Natal'),
('Msinga, KwaZulu-Natal'),
('Msukaligwa, Mpumalanga'),
('Mthonjaneni, KwaZulu-Natal'),
('Mtubatuba, KwaZulu-Natal'),
('Musina, Limpopo'),
('Mutale, Limpopo'),
('Nala, Free State'),
('Naledi, Free State'),
('Naledi, North West'),
('Nama Khoi, Northern Cape'),
('Ndlambe, Eastern Cape'),
('Ndwedwe, KwaZulu-Natal'),
('Nelson Mandela Bay, Eastern Cape'),
('Newcastle, KwaZulu-Natal'),
('Ngqushwa, Eastern Cape'),
('Ngquza Hill, Eastern Cape'),
('Ngwathe, Free State'),
('Nkandla, KwaZulu-Natal'),
('Nketoana, Free State'),
('Nkomazi, Mpumalanga'),
('Nkonkobe, Eastern Cape'),
('Nongoma, KwaZulu-Natal'),
('Nqutu, KwaZulu-Natal'),
('Ntabankulu, Eastern Cape'),
('Ntambanana, KwaZulu-Natal'),
('Nxuba, Eastern Cape'),
('Nyandeni, Eastern Cape'),
('Okhahlamba, KwaZulu-Natal'),
('Oudtshoorn, Western Cape'),
('Overstrand, Western Cape'),
('Phokwane, Northern Cape'),
('Phumelela, Free State'),
('Polokwane, Limpopo'),
('Port St Johns, Eastern Cape'),
('Prince Albert, Western Cape'),
('Ramotshere Moiloa, North West'),
('Rand West City, Gauteng'),
('Randfontein, Gauteng'),
('Ratlou, North West'),
('Ray Nkonyeni, KwaZulu-Natal'),
('Raymond Mhlaba, Eastern Cape'),
('Renosterberg, Northern Cape'),
('Richmond, KwaZulu-Natal'),
('Richtersveld, Northern Cape'),
('Rustenburg, North West'),
('Sakhisizwe, Eastern Cape'),
('Saldanha Bay, Western Cape'),
('Senqu, Eastern Cape'),
('Setsoto, Free State'),
('Siyancuma, Northern Cape'),
('Siyathemba, Northern Cape'),
('Sol Plaatjie, Northern Cape'),
('Stellenbosch, Western Cape'),
('Steve Tshwete, Mpumalanga'),
('Sundays River Valley, Eastern Cape'),
('Swartland, Western Cape'),
('Swellendam, Western Cape'),
('Thaba Chweu, Mpumalanga'),
('Thabazimbi, Limpopo'),
('The Big 5 False Bay, KwaZulu-Natal'),
('The Msunduzi, KwaZulu-Natal'),
('Theewaterskloof, Western Cape'),
('Thembelihle, Northern Cape'),
('Thembisile, Mpumalanga'),
('Thulamela, Limpopo'),
('Tlokwe City Council, North West'),
('Tokologo, Free State'),
('Tsantsabane, Northern Cape'),
('Tsolwana, Eastern Cape'),
('Tswaing, North West'),
('Tswelopele, Free State'),
('Ubuhlebezwe, KwaZulu-Natal'),
('Ubuntu, Northern Cape'),
('Ulundi, KwaZulu-Natal'),
('Umdoni, KwaZulu-Natal'),
('Umhlabuyalingana, KwaZulu-Natal'),
('Umjindi, Mpumalanga'),
('Umsobomvu, Northern Cape'),
('Umtshezi, KwaZulu-Natal'),
('Umvoti, KwaZulu-Natal'),
('Umzimkhulu, KwaZulu-Natal'),
('Umzimvubu, Eastern Cape'),
('Umzumbe, KwaZulu-Natal'),
('Ventersdorp, North West'),
('Ventersdorp/Tlokwe, North West'),
('Victor Khanye, Mpumalanga'),
('Vulamehlo, KwaZulu-Natal'),
('Walter Sisulu, Eastern Cape'),
('Westonaria, Gauteng'),
('Witzenberg, Western Cape'),
('eDumbe, KwaZulu-Natal'),
('eThekwini, KwaZulu-Natal'),
('uMhlathuze, KwaZulu-Natal'),
('uMlalazi, KwaZulu-Natal'),
('uMngeni, KwaZulu-Natal'),
('uMshwathi, KwaZulu-Natal'),
('uMuziwabantu, KwaZulu-Natal'),
('uPhongolo, KwaZulu-Natal')
)l(s)
inner join [Municipality] m on l.s like m.Mun_Name+'%' --like s
inner join --select * from
Province p on replace(l.s,'-',' ') like '%'+p.Prov_name


select *
from Municipality
where Mun_Type_Id=500